on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Publish package
      run: | 
        poetry publish -vvv \
        --username ${{ secrets.PYPI_USERNAME }} \
        --password ${{ secrets.PYPI_PASSWORD }} \
        --build
