on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  bump_version:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
    outputs:
      outcome: ${{ steps.cz.outcome }}
      conclusion: ${{ steps.cz.conclusion }}

  release:
    # if a bump version failed or was not executed, do not release
    needs: bump_version
    runs-on: ubuntu-latest
    if: needs.bump_version.outputs.outcome == 'success' || needs.bump_version.outputs.conclusion == 'success'
    steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Publish package
      run: | 
        poetry publish -vvv \
        --username ${{ secrets.PYPI_USERNAME }} \
        --password ${{ secrets.PYPI_PASSWORD }} \
        --build
